# Generated by Django 6.0.2 on 2026-02-12 12:02

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_orderaddress'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='orderaddress',
            options={'ordering': ['-is_default', '-updated_at'], 'verbose_name': 'آدرس سفارش', 'verbose_name_plural': 'آدرس\u200cهای سفارش'},
        ),
        migrations.AlterModelOptions(
            name='phoneotp',
            options={'verbose_name': 'کد OTP', 'verbose_name_plural': 'کدهای OTP'},
        ),
        migrations.AlterModelOptions(
            name='profile',
            options={'verbose_name': 'پروفایل', 'verbose_name_plural': 'پروفایل\u200cها'},
        ),
        migrations.AlterField(
            model_name='orderaddress',
            name='city',
            field=models.CharField(max_length=80, verbose_name='شهر'),
        ),
        migrations.AlterField(
            model_name='orderaddress',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='تاریخ ایجاد'),
        ),
        migrations.AlterField(
            model_name='orderaddress',
            name='full_name',
            field=models.CharField(max_length=150, verbose_name='نام کامل'),
        ),
        migrations.AlterField(
            model_name='orderaddress',
            name='is_default',
            field=models.BooleanField(default=False, verbose_name='آدرس پیش\u200cفرض'),
        ),
        migrations.AlterField(
            model_name='orderaddress',
            name='label',
            field=models.CharField(blank=True, default='', max_length=80, verbose_name='برچسب'),
        ),
        migrations.AlterField(
            model_name='orderaddress',
            name='phone',
            field=models.CharField(max_length=32, verbose_name='تلفن'),
        ),
        migrations.AlterField(
            model_name='orderaddress',
            name='postal_code',
            field=models.CharField(blank=True, default='', max_length=20, verbose_name='کدپستی'),
        ),
        migrations.AlterField(
            model_name='orderaddress',
            name='province',
            field=models.CharField(max_length=80, verbose_name='استان'),
        ),
        migrations.AlterField(
            model_name='orderaddress',
            name='street_address',
            field=models.TextField(verbose_name='آدرس'),
        ),
        migrations.AlterField(
            model_name='orderaddress',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='آخرین ویرایش'),
        ),
        migrations.AlterField(
            model_name='orderaddress',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_addresses', to=settings.AUTH_USER_MODEL, verbose_name='کاربر'),
        ),
        migrations.AlterField(
            model_name='phoneotp',
            name='attempts',
            field=models.IntegerField(default=0, verbose_name='تلاش\u200cها'),
        ),
        migrations.AlterField(
            model_name='phoneotp',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='تاریخ ایجاد'),
        ),
        migrations.AlterField(
            model_name='phoneotp',
            name='last_sent_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='آخرین ارسال'),
        ),
        migrations.AlterField(
            model_name='phoneotp',
            name='locked_until',
            field=models.DateTimeField(blank=True, null=True, verbose_name='قفل تا'),
        ),
        migrations.AlterField(
            model_name='phoneotp',
            name='otp_hmac',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='کد HMAC'),
        ),
        migrations.AlterField(
            model_name='phoneotp',
            name='phone',
            field=models.CharField(max_length=32, unique=True, verbose_name='شماره تلفن'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='phone',
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name='شماره تلفن'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='کاربر'),
        ),
    ]
