# Generated by Django 6.0.2 on 2026-02-13 22:33

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_orderaddress_options_alter_phoneotp_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PendingProfileChange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('change_type', models.CharField(choices=[('phone', 'شماره موبایل'), ('email', 'ایمیل')], max_length=10, verbose_name='نوع تغییر')),
                ('new_value', models.CharField(max_length=255, verbose_name='مقدار جدید')),
                ('code_hmac', models.CharField(max_length=256, verbose_name='HMAC کد')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='ایجاد')),
                ('attempts', models.IntegerField(default=0, verbose_name='تلاش')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pending_changes', to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'تغییر در انتظار تایید',
                'verbose_name_plural': 'تغییرات در انتظار تایید',
                'unique_together': {('user', 'change_type')},
            },
        ),
    ]
