# Generated by Django 6.0.2 on 2026-02-05 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sitesettings',
            options={'verbose_name': 'Site Settings', 'verbose_name_plural': 'Site Settings'},
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='sms_enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='support_email_notifications_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='support_notify_email',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='telegram_admin_url',
            field=models.CharField(blank=True, default='https://t.me/accountinox_admin', max_length=255),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='telegram_channel_url',
            field=models.CharField(blank=True, default='https://t.me/accountinox', max_length=255),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='telegram_support_label',
            field=models.CharField(blank=True, default='پشتیبانی در تلگرام', max_length=100),
        ),
    ]
