# Generated by Django 6.0.2 on 2026-02-12 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_sitesettings_brand_wordmark_fa'),
    ]

    operations = [
        migrations.CreateModel(
            name='HeroBanner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='خط اول عنوان بنر — مثلاً «اکانت\u200cهای پریمیوم»', max_length=120, verbose_name='عنوان اصلی')),
                ('title_highlight', models.CharField(blank=True, help_text='خط دوم عنوان که با رنگ گرادیان نمایش داده می\u200cشود — مثلاً «با تضمین کیفیت»', max_length=120, verbose_name='عنوان رنگی (گرادیان)')),
                ('description', models.TextField(blank=True, help_text='متن زیر عنوان — حداکثر ۳۰۰ کاراکتر', max_length=300, verbose_name='توضیحات')),
                ('badge_text', models.CharField(blank=True, help_text='متن کنار آیکون بالای عنوان — مثلاً «تحویل فوری · پشتیبانی ۲۴ ساعته»', max_length=80, verbose_name='متن بج')),
                ('badge_color', models.CharField(choices=[('primary', 'سبز (Primary)'), ('amber', 'زرد / نارنجی (Amber)'), ('emerald', 'سبز روشن (Emerald)'), ('sky', 'آبی (Sky)'), ('red', 'قرمز (Red)'), ('violet', 'بنفش (Violet)')], default='primary', max_length=20, verbose_name='رنگ بج')),
                ('button_text', models.CharField(blank=True, default='مشاهده محصولات', max_length=60, verbose_name='متن دکمه اصلی')),
                ('button_url', models.CharField(blank=True, default='/shop/', max_length=300, verbose_name='لینک دکمه اصلی')),
                ('button2_text', models.CharField(blank=True, help_text='اختیاری — خالی بگذارید اگر فقط یک دکمه می\u200cخواهید', max_length=60, verbose_name='متن دکمه دوم')),
                ('button2_url', models.CharField(blank=True, max_length=300, verbose_name='لینک دکمه دوم')),
                ('background_image', models.ImageField(blank=True, help_text='اختیاری — در صورت آپلود، جایگزین گرادیان پیش\u200cفرض می\u200cشود', null=True, upload_to='banners/', verbose_name='تصویر پس\u200cزمینه')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('order', models.PositiveIntegerField(default=0, help_text='عدد کوچک\u200cتر = نمایش زودتر', verbose_name='ترتیب نمایش')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخرین ویرایش')),
            ],
            options={
                'verbose_name': 'بنر اسلایدر',
                'verbose_name_plural': 'بنرهای اسلایدر',
                'ordering': ['order', '-created_at'],
            },
        ),
    ]
