# Generated by Django 6.0.2 on 2026-02-12 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_herobanner'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeatureCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.CharField(choices=[('bolt', 'رعد و برق (تحویل آنی)'), ('shield', 'سپر (تضمین)'), ('headset', 'هدست (پشتیبانی)'), ('dollar', 'دلار (قیمت)'), ('star', 'ستاره'), ('lock', 'قفل (امنیت)'), ('rocket', 'موشک'), ('gift', 'هدیه')], default='bolt', max_length=30, verbose_name='آیکون')),
                ('title', models.CharField(max_length=100, verbose_name='عنوان')),
                ('description', models.TextField(max_length=300, verbose_name='توضیحات')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='ترتیب')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
            ],
            options={
                'verbose_name': 'کارت ویژگی',
                'verbose_name_plural': 'کارت\u200cهای ویژگی',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='FooterLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('column', models.CharField(choices=[('quick', 'دسترسی سریع'), ('legal', 'قوانین')], default='quick', max_length=20, verbose_name='ستون')),
                ('label', models.CharField(max_length=100, verbose_name='عنوان لینک')),
                ('url', models.CharField(max_length=300, verbose_name='آدرس')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='ترتیب')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('open_new_tab', models.BooleanField(default=False, verbose_name='باز شدن در تب جدید')),
            ],
            options={
                'verbose_name': 'لینک فوتر',
                'verbose_name_plural': 'لینک\u200cهای فوتر',
                'ordering': ['column', 'order'],
            },
        ),
        migrations.CreateModel(
            name='TrustStat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.CharField(choices=[('users', 'کاربران'), ('headset', 'پشتیبانی'), ('shield', 'امنیت'), ('star', 'ستاره'), ('check', 'تیک'), ('clock', 'ساعت'), ('truck', 'ارسال'), ('heart', 'قلب')], default='check', max_length=30, verbose_name='آیکون')),
                ('value', models.CharField(help_text='مثلاً «+۱۰,۰۰۰» یا «۲۴/۷» یا «۱۰۰٪»', max_length=40, verbose_name='مقدار')),
                ('label', models.CharField(help_text='مثلاً «مشتری راضی» یا «پشتیبانی آنلاین»', max_length=80, verbose_name='برچسب')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='ترتیب')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
            ],
            options={
                'verbose_name': 'آمار اعتماد',
                'verbose_name_plural': 'آمارهای اعتماد',
                'ordering': ['order'],
            },
        ),
        migrations.AlterModelOptions(
            name='globalfaq',
            options={'ordering': ['ordering'], 'verbose_name': 'سوال متداول', 'verbose_name_plural': 'سوالات متداول'},
        ),
        migrations.AlterModelOptions(
            name='sitesettings',
            options={'verbose_name': 'تنظیمات سایت', 'verbose_name_plural': 'تنظیمات سایت'},
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='cta_button1_text',
            field=models.CharField(blank=True, default='شروع گفتگو', max_length=60, verbose_name='دکمه ۱ CTA'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='cta_button1_url',
            field=models.CharField(blank=True, default='/support/chat/', max_length=300, verbose_name='لینک دکمه ۱ CTA'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='cta_button2_text',
            field=models.CharField(blank=True, default='تماس با ما', max_length=60, verbose_name='دکمه ۲ CTA'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='cta_button2_url',
            field=models.CharField(blank=True, default='/contact/', max_length=300, verbose_name='لینک دکمه ۲ CTA'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='cta_description',
            field=models.CharField(blank=True, default='تیم پشتیبانی ما آماده پاسخگویی به تمام سوالات شماست.', max_length=300, verbose_name='توضیح CTA'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='cta_title',
            field=models.CharField(blank=True, default='سوالی دارید؟ ما اینجاییم.', max_length=120, verbose_name='عنوان CTA'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='email',
            field=models.EmailField(blank=True, default='', max_length=254, verbose_name='ایمیل'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='features_subtitle',
            field=models.CharField(blank=True, default='سادگی در خرید، سرعت در تحویل و اطمینان در کیفیت.', max_length=250, verbose_name='زیرعنوان بخش ویژگی\u200cها'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='features_title',
            field=models.CharField(blank=True, default='چرا اکانتینوکس؟', max_length=120, verbose_name='عنوان بخش ویژگی\u200cها'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='footer_copyright',
            field=models.CharField(blank=True, default='تمامی حقوق محفوظ است.', max_length=200, verbose_name='متن کپی\u200cرایت'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='footer_developer_name',
            field=models.CharField(blank=True, default='رامین جلیلی', max_length=100, verbose_name='نام توسعه\u200cدهنده'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='footer_developer_url',
            field=models.CharField(blank=True, default='', max_length=300, verbose_name='لینک توسعه\u200cدهنده'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='instagram_url',
            field=models.CharField(blank=True, default='', max_length=300, verbose_name='لینک اینستاگرام'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='phone',
            field=models.CharField(blank=True, default='', max_length=32, verbose_name='شماره تماس'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='products_subtitle',
            field=models.CharField(blank=True, default='محبوب\u200cترین اکانت\u200cهای پریمیوم با تحویل فوری.', max_length=250, verbose_name='زیرعنوان بخش محصولات'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='products_title',
            field=models.CharField(blank=True, default='جدیدترین محصولات', max_length=120, verbose_name='عنوان بخش محصولات'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='site_description',
            field=models.TextField(blank=True, default='', help_text='توضیح کوتاه — نمایش در فوتر و متا تگ\u200cها', verbose_name='توضیح سایت'),
        ),
        migrations.AlterField(
            model_name='globalfaq',
            name='answer',
            field=models.TextField(verbose_name='پاسخ'),
        ),
        migrations.AlterField(
            model_name='globalfaq',
            name='ordering',
            field=models.IntegerField(default=0, verbose_name='ترتیب'),
        ),
        migrations.AlterField(
            model_name='globalfaq',
            name='question',
            field=models.CharField(max_length=255, verbose_name='سوال'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='accent_color',
            field=models.CharField(default='#45E2CC', max_length=7, verbose_name='رنگ تاکیدی'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='brand_wordmark_fa',
            field=models.CharField(blank=True, default='اکانتینوکس', max_length=150, verbose_name='نام فارسی برند'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='chat_mode',
            field=models.CharField(choices=[('ws', 'WebSocket'), ('poll', 'Polling')], default='poll', max_length=10, verbose_name='حالت چت'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='enamad_html',
            field=models.TextField(blank=True, default='', help_text='کد اینماد و سایر نمادهای اعتماد', verbose_name='کد HTML اینماد'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='logos/', verbose_name='لوگو'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='otp_enabled',
            field=models.BooleanField(default=True, verbose_name='OTP فعال'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='otp_expiry_seconds',
            field=models.IntegerField(default=300, verbose_name='مدت اعتبار OTP (ثانیه)'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='otp_for_sensitive',
            field=models.BooleanField(default=False, verbose_name='OTP برای عملیات حساس'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='otp_max_attempts',
            field=models.IntegerField(default=5, verbose_name='حداکثر تلاش OTP'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='otp_resend_cooldown',
            field=models.IntegerField(default=60, verbose_name='فاصله ارسال مجدد OTP (ثانیه)'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='payment_gateway',
            field=models.CharField(blank=True, default='zarinpal', max_length=50, verbose_name='درگاه پرداخت'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='primary_color',
            field=models.CharField(default='#1ABBC8', max_length=7, verbose_name='رنگ اصلی'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='secondary_color',
            field=models.CharField(default='#0468BD', max_length=7, verbose_name='رنگ ثانویه'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='site_name',
            field=models.CharField(default='Accountinox', max_length=150, verbose_name='نام سایت'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='sms_enabled',
            field=models.BooleanField(default=True, verbose_name='ارسال SMS فعال'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='sms_provider',
            field=models.CharField(blank=True, default='console', max_length=100, verbose_name='ارسال\u200cکننده SMS'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='support_email_notifications_enabled',
            field=models.BooleanField(default=False, verbose_name='اعلان ایمیلی پشتیبانی'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='support_notify_email',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='ایمیل اعلان پشتیبانی'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='tailwind_mode',
            field=models.CharField(choices=[('cdn', 'CDN'), ('local', 'فایل محلی')], default='cdn', max_length=10, verbose_name='حالت Tailwind'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='telegram_admin_url',
            field=models.CharField(blank=True, default='https://t.me/accountinox_admin', max_length=255, verbose_name='لینک تلگرام ادمین'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='telegram_channel_url',
            field=models.CharField(blank=True, default='https://t.me/accountinox', max_length=255, verbose_name='لینک کانال تلگرام'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='telegram_support_label',
            field=models.CharField(blank=True, default='پشتیبانی در تلگرام', max_length=100, verbose_name='برچسب پشتیبانی تلگرام'),
        ),
    ]
