# Generated by Django 6.0.2 on 2026-02-12 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_featurecard_footerlink_truststat_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitesettings',
            name='cta_button1_url',
            field=models.CharField(blank=True, default='/support/', max_length=300, verbose_name='لینک دکمه ۱ CTA'),
        ),
    ]
