# Generated by Django 6.0.2 on 2026-02-13 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_sitesettings_cta_button1_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitesettings',
            name='otp_expiry_seconds',
            field=models.IntegerField(default=120, verbose_name='مدت اعتبار OTP (ثانیه)'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='otp_max_attempts',
            field=models.IntegerField(default=3, verbose_name='حداکثر تلاش OTP'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='otp_resend_cooldown',
            field=models.IntegerField(default=120, verbose_name='فاصله ارسال مجدد OTP (ثانیه)'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='sms_provider',
            field=models.CharField(blank=True, choices=[('console', 'Console (log only)'), ('kavenegar', 'Kavenegar'), ('ippanel', 'IPPanel / Edge')], default='console', help_text='انتخاب سرویس ارسال پیامک', max_length=100, verbose_name='ارسال\u200cکننده SMS'),
        ),
    ]
