# Generated by Django 6.0.2 on 2026-02-13 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_sitesettings_otp_expiry_seconds_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='order_email_footer',
            field=models.TextField(blank=True, default='در صورت هرگونه سوال، با پشتیبانی ما در تماس باشید.', help_text='متن زیر فاکتور در ایمیل', verbose_name='متن پایانی ایمیل سفارش'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='order_email_intro',
            field=models.TextField(blank=True, default='با تشکر از خرید شما! سفارش شما با موفقیت ثبت و پرداخت شد.', help_text='متن بالای فاکتور در ایمیل', verbose_name='متن مقدمه ایمیل سفارش'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='order_sms_enabled',
            field=models.BooleanField(default=False, help_text='در صورت فعال بودن، پس از پرداخت موفق پیامک ارسال می\u200cشود', verbose_name='ارسال پیامک پس از خرید'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='order_sms_text',
            field=models.TextField(blank=True, default='سفارش شما با کد {order_number} با موفقیت ثبت شد. با تشکر از خرید شما.', help_text='از {order_number} برای درج شماره سفارش استفاده کنید', verbose_name='متن پیامک سفارش'),
        ),
    ]
