# Generated by Django 6.0.2 on 2026-02-17 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_sitebackup'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='google_oauth_button_text',
            field=models.CharField(blank=True, default='ادامه با گوگل', max_length=80, verbose_name='متن دکمه ورود با گوگل'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='google_oauth_enabled',
            field=models.BooleanField(default=False, help_text='در صورت فعال بودن و کامل بودن تنظیمات OAuth، دکمه گوگل در ورود/ثبت\u200cنام نمایش داده می\u200cشود.', verbose_name='فعال\u200cسازی ورود با گوگل'),
        ),
    ]
