# Generated by Django 6.0.2 on 2026-02-18 11:15

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_sitesettings_google_oauth_button_text_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='vat_enabled',
            field=models.BooleanField(default=True, help_text='در صورت فعال بودن، درصد مالیات بر جمع جزء سفارش افزوده می\u200cشود.', verbose_name='مالیات بر ارزش افزوده فعال'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='vat_percent',
            field=models.PositiveSmallIntegerField(default=10, help_text='به\u200cصورت درصد. مقدار پیش\u200cفرض ۱۰ است.', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='درصد مالیات بر ارزش افزوده'),
        ),
    ]
