# Generated by Django 6.0.2 on 2026-02-19 14:46

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_sitesettings_vat_enabled_sitesettings_vat_percent'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='support_sla_breach_seconds',
            field=models.PositiveIntegerField(default=900, help_text='پس از این زمان، گفتگوی بی\u200cپاسخ در وضعیت «بحرانی / SLA نقض شده» نمایش داده می\u200cشود.', validators=[django.core.validators.MinValueValidator(60), django.core.validators.MaxValueValidator(172800)], verbose_name='آستانه SLA بحرانی (ثانیه)'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='support_sla_warning_seconds',
            field=models.PositiveIntegerField(default=300, help_text='پس از این زمان، گفتگوی بی\u200cپاسخ در وضعیت «فوری» نمایش داده می\u200cشود.', validators=[django.core.validators.MinValueValidator(30), django.core.validators.MaxValueValidator(86400)], verbose_name='آستانه SLA فوری (ثانیه)'),
        ),
    ]
