# Generated by Django 6.0.2 on 2026-02-12 16:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0004_alter_supportcontact_options_chatsession_assigned_to_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chatmessage',
            options={'ordering': ['created_at'], 'verbose_name': 'پیام چت', 'verbose_name_plural': 'پیام\u200cهای چت'},
        ),
        migrations.AlterModelOptions(
            name='chatsession',
            options={'ordering': ['-created_at'], 'verbose_name': 'جلسه گفتگو', 'verbose_name_plural': 'جلسات گفتگو'},
        ),
        migrations.AlterModelOptions(
            name='supportauditlog',
            options={'ordering': ['-created_at'], 'verbose_name': 'لاگ عملیات', 'verbose_name_plural': 'لاگ\u200cهای عملیات'},
        ),
        migrations.AlterModelOptions(
            name='supportcontact',
            options={'ordering': ['-updated_at'], 'permissions': (('can_export_support_contacts', 'Can export support contacts'),), 'verbose_name': 'مخاطب پشتیبانی', 'verbose_name_plural': 'مخاطبین پشتیبانی'},
        ),
        migrations.AlterModelOptions(
            name='supportoperatorpresence',
            options={'ordering': ['-last_seen_at'], 'verbose_name': 'حضور اپراتور', 'verbose_name_plural': 'حضور اپراتورها'},
        ),
        migrations.AlterModelOptions(
            name='supportpushsubscription',
            options={'ordering': ['-updated_at'], 'verbose_name': 'اشتراک پوش', 'verbose_name_plural': 'اشتراک\u200cهای پوش'},
        ),
        migrations.AlterModelOptions(
            name='supportrating',
            options={'ordering': ['-created_at'], 'permissions': (('view_all_support_ratings', 'Can view all support ratings'),), 'verbose_name': 'امتیاز پشتیبانی', 'verbose_name_plural': 'امتیازهای پشتیبانی'},
        ),
    ]
