# Generated by Django 6.0.2 on 2026-02-06 08:26

import apps.shop.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_product_featured_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='featured_image',
            field=models.ImageField(blank=True, null=True, upload_to='products/', validators=[apps.shop.models.validate_image_file]),
        ),
    ]
