# Generated by Django 6.0.2 on 2026-02-13 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_alter_product_options_product_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_number',
            field=models.CharField(blank=True, max_length=30, unique=True, verbose_name='شماره سفارش'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='customer_email',
            field=models.EmailField(blank=True, default='', max_length=254, verbose_name='ایمیل مشتری (برای حساب)'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='customer_password',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='رمز عبور مشتری (برای حساب)'),
        ),
        migrations.AddField(
            model_name='product',
            name='credential_label',
            field=models.CharField(blank=True, help_text='مثلاً «ایمیل اکانت نتفلیکس» — اگر خالی باشد از پیش\u200cفرض استفاده می\u200cشود', max_length=120, verbose_name='برچسب فیلد اطلاعات'),
        ),
        migrations.AddField(
            model_name='product',
            name='credential_type',
            field=models.CharField(choices=[('none', 'نیازی نیست'), ('email', 'فقط ایمیل'), ('email_pass', 'ایمیل و رمز عبور')], default='none', help_text='آیا مشتری باید ایمیل/رمز حسابش را هنگام خرید وارد کند؟', max_length=20, verbose_name='اطلاعات حساب مشتری'),
        ),
        migrations.AddField(
            model_name='product',
            name='features',
            field=models.TextField(blank=True, help_text='هر ویژگی در یک خط (خط\u200cبه\u200cخط نمایش داده می\u200cشود)', verbose_name='ویژگی\u200cها'),
        ),
        migrations.AddField(
            model_name='product',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='فعال'),
        ),
        migrations.AddField(
            model_name='product',
            name='short_description',
            field=models.CharField(blank=True, help_text='توضیح کوتاه برای کارت محصول (حداکثر ۳۰۰ کاراکتر)', max_length=300, verbose_name='خلاصه توضیحات'),
        ),
    ]
