# Generated by Django 6.0.2 on 2026-02-14 00:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0009_product_is_available_cartitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='quantity',
            field=models.PositiveIntegerField(default=1, verbose_name='تعداد'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='region_name',
            field=models.CharField(blank=True, default='', help_text='نام ریجن در زمان خرید', max_length=120, verbose_name='ریجن انتخابی'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='variant_name',
            field=models.CharField(blank=True, default='', help_text='نام تنوع در زمان خرید (مثلاً ۳ ماهه)', max_length=120, verbose_name='تنوع انتخابی'),
        ),
        migrations.AddField(
            model_name='product',
            name='allow_quantity',
            field=models.BooleanField(default=False, help_text='اگر فعال شود، مشتری می\u200cتواند تعداد دلخواه سفارش دهد', verbose_name='انتخاب تعداد توسط مشتری'),
        ),
        migrations.AddField(
            model_name='product',
            name='delivery_type',
            field=models.CharField(choices=[('manual', 'تحویل دستی (ادمین انجام می\u200cدهد)'), ('digital', 'فایل دانلودی (خودکار پس از پرداخت)')], default='manual', help_text='تحویل دستی: ادمین بررسی و انجام می\u200cدهد. فایل دانلودی: مشتری پس از پرداخت دانلود می\u200cکند.', max_length=20, verbose_name='نحوه تحویل'),
        ),
        migrations.AddField(
            model_name='product',
            name='digital_file',
            field=models.FileField(blank=True, help_text='فایلی که پس از پرداخت موفق برای مشتری قابل دانلود می\u200cشود', null=True, upload_to='products/digital/', verbose_name='فایل دانلودی'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='قیمت واحد'),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=2, help_text='اگر تنوع قیمتی دارد، قیمت هر تنوع جداگانه تنظیم می\u200cشود. این قیمت پیش\u200cفرض است.', max_digits=10, verbose_name='قیمت پایه'),
        ),
        migrations.CreateModel(
            name='ProductRegion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='مثلاً «آمریکا»، «اروپا»، «ترکیه»', max_length=120, verbose_name='نام ریجن')),
                ('sort_order', models.IntegerField(default=0, verbose_name='ترتیب نمایش')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='regions', to='shop.product', verbose_name='محصول')),
            ],
            options={
                'verbose_name': 'ریجن',
                'verbose_name_plural': 'ریجن\u200cها',
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.AddField(
            model_name='cartitem',
            name='region',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='shop.productregion', verbose_name='ریجن انتخابی'),
        ),
        migrations.CreateModel(
            name='ProductVariant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='مثلاً «۱ ماهه»، «۳ ماهه»، «۱ ساله»', max_length=120, verbose_name='نام تنوع')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='قیمت')),
                ('sort_order', models.IntegerField(default=0, verbose_name='ترتیب نمایش')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='shop.product', verbose_name='محصول')),
            ],
            options={
                'verbose_name': 'تنوع قیمتی',
                'verbose_name_plural': 'تنوع\u200cهای قیمتی',
                'ordering': ['sort_order', 'price'],
            },
        ),
        migrations.AddField(
            model_name='cartitem',
            name='variant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='shop.productvariant', verbose_name='تنوع انتخابی'),
        ),
    ]
