# Generated by Django 6.0.2 on 2026-02-14 07:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0010_orderitem_quantity_orderitem_region_name_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productvariant',
            options={'ordering': ['region__sort_order', 'region__name', 'sort_order', 'price'], 'verbose_name': 'تنوع قیمتی', 'verbose_name_plural': 'تنوع\u200cهای قیمتی'},
        ),
        migrations.AddField(
            model_name='productvariant',
            name='region',
            field=models.ForeignKey(blank=True, help_text='اگر محصول ریجن دارد، این تنوع متعلق به کدام ریجن است؟', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='shop.productregion', verbose_name='ریجن'),
        ),
    ]
