# Generated by Django 6.0.2 on 2026-02-14 23:37

import apps.shop.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0011_variant_region_fk'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='featured_image',
            field=models.ImageField(blank=True, help_text='لوگو یا تصویر سرویس (نمایش در صفحه اصلی و لیست سرویس\u200cها)', null=True, upload_to='services/', validators=[apps.shop.models.validate_image_file], verbose_name='تصویر / لوگو'),
        ),
        migrations.AlterField(
            model_name='service',
            name='icon',
            field=models.CharField(blank=True, help_text='اختیاری — اگر تصویر آپلود شود، از تصویر استفاده می\u200cشود.', max_length=120, verbose_name='آیکون CSS'),
        ),
    ]
