# Generated by Django 6.0.2 on 2026-02-17 22:58

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0012_service_featured_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='discount_enabled',
            field=models.BooleanField(default=False, verbose_name='تخفیف فعال'),
        ),
        migrations.AddField(
            model_name='product',
            name='discount_end_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='پایان تخفیف'),
        ),
        migrations.AddField(
            model_name='product',
            name='discount_percent',
            field=models.PositiveSmallIntegerField(default=0, help_text='درصد تخفیف بین ۰ تا ۱۰۰.', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='درصد تخفیف'),
        ),
        migrations.AddField(
            model_name='product',
            name='discount_start_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='شروع تخفیف'),
        ),
    ]
