# Generated by Django 6.0.2 on 2026-02-17 22:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0013_product_discount_fields'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['-created_at'], 'verbose_name': 'خدمت', 'verbose_name_plural': 'خدمات'},
        ),
        migrations.AlterModelOptions(
            name='service',
            options={'ordering': ('order', 'name'), 'verbose_name': 'گروه خدمات', 'verbose_name_plural': 'گروه\u200cهای خدمات'},
        ),
        migrations.AlterField(
            model_name='accountitem',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='shop.product', verbose_name='خدمت'),
        ),
        migrations.AlterField(
            model_name='cartitem',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.product', verbose_name='خدمت'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='shop.product', verbose_name='خدمت'),
        ),
        migrations.AlterField(
            model_name='product',
            name='is_available',
            field=models.BooleanField(default=True, help_text='اگر غیرفعال شود، خدمت نمایش داده می\u200cشود ولی قابل خرید نیست (ناموجود)', verbose_name='موجود'),
        ),
        migrations.AlterField(
            model_name='product',
            name='short_description',
            field=models.CharField(blank=True, help_text='توضیح کوتاه برای کارت خدمت (حداکثر ۳۰۰ کاراکتر)', max_length=300, verbose_name='خلاصه توضیحات'),
        ),
        migrations.AlterField(
            model_name='productregion',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='regions', to='shop.product', verbose_name='خدمت'),
        ),
        migrations.AlterField(
            model_name='productvariant',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='shop.product', verbose_name='خدمت'),
        ),
        migrations.AlterField(
            model_name='productvariant',
            name='region',
            field=models.ForeignKey(blank=True, help_text='اگر خدمت ریجن دارد، این تنوع متعلق به کدام ریجن است؟', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='shop.productregion', verbose_name='ریجن'),
        ),
    ]
