# Generated by Django 6.0.2 on 2026-02-18 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0014_alter_product_options_alter_service_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='subtotal_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='جمع جزء'),
        ),
        migrations.AddField(
            model_name='order',
            name='vat_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='مبلغ مالیات بر ارزش افزوده'),
        ),
        migrations.AddField(
            model_name='order',
            name='vat_percent_applied',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='درصد مالیات اعمال\u200cشده'),
        ),
    ]
